imports:
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: "1.1.0"
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true
    session:
         save_path: "%kernel.root_dir%/sessions"

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:      %database_driver%
        host:        %database_host%
        port:        %database_port%
        unix_socket: %database_socket%
        dbname:      %database_name%
        user:        %database_user%
        password:    %database_password%
        charset:     UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# SWP Configuration
swp_frontend:
    contact_email:     %contact_email%
    contact_receivers: %contact_receivers%

# Gregwar Configuration
gregwar_captcha: ~

# Meetup Configuration
dms_meetup_api:
    client:
        key: %meetup_api_key%
