---

- src: f500.bashrc
- src: f500.debian
- src: f500.repo_dotdeb
- src: f500.nginx
- src: f500.mariadb55
- src: f500.php
- src: f500.php_cli
- src: f500.php_fpm
- src: f500.php_extensions
- src: f500.php_composer
- src: f500.ufw
- src: f500.ufw_rules
- src: f500.php_xdebug
- src: f500.project_deploy
