---
- name: Deploy the application
  hosts: production
  remote_user: deploy
  sudo: no

  vars:
    project_root: "{{ sweetlakephp_root }}"
    project_github_repo: "{{ sweetlakephp_github_repo }}"

    project_environment:
      SYMFONY_ENV: "prod"

    project_shared_children:
      - path: "/app/sessions"
        src: "sessions"
      - path: "/web/uploads"
        src: "uploads"

    project_templates:
      - name: parameters.yml
        src: "templates/parameters_prod.yml.j2"
        dest: "/app/config/parameters_prod.yml"

    project_has_composer: yes

    project_post_dependency_commands:
      - "php vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Resources/bin/build_bootstrap.php"
      - "app/console cache:clear"
      - "app/console doctrine:migrations:migrate --no-interaction"
      - "app/console assets:install"
      - "app/console assetic:dump"

  roles:
    - project-deploy

  post_tasks:
    - name: Remove old releases
      deploy: "path={{ project_root }} state=cleanup"
