---
- name: Deploy the application
  hosts: production
  remote_user: "{{ production_deploy_user }}"
  sudo: no

  vars:
    project_root: "{{ sweetlakephp_root }}"
    project_git_repo: "{{ sweetlakephp_github_repo }}"
    project_deploy_strategy: git

    project_environment:
      SYMFONY_ENV: "prod"

    project_shared_children:
      - path: "/app/sessions"
        src: "sessions"
      - path: "/web/uploads"
        src: "uploads"

    project_templates:
      - name: parameters.yml
        src: "templates/parameters_prod.yml.j2"
        dest: "/app/config/parameters_prod.yml"

    project_has_composer: yes

    project_post_build_commands:
      - "php vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Resources/bin/build_bootstrap.php"
      - "app/console cache:clear"
      - "app/console doctrine:migrations:migrate --no-interaction"
      - "app/console assets:install"
      - "app/console assetic:dump"

  roles:
    - f500.project_deploy

  post_tasks:
    - name: Remove old releases
      deploy: "path={{ project_root }} state=clean"

    - name: retrieve local user
      local_action: command whoami
      register: local_user

    - name: Whoohoo!
      slack: domain=future500.slack.com msg="Version {{ project_version }} of {{ project_git_repo }} deployed on {{ inventory_hostname }} by {{ local_user.stdout }}!" token={{ slack_api_token }}
