---
- name: Deploy the application
  hosts: production
  remote_user: "{{ production_deploy_user }}"

  vars:
    project_root: "{{ sweetlakephp_root }}"
    project_git_repo: "{{ sweetlakephp_github_repo }}"
    project_deploy_strategy: git

    project_environment:
      SYMFONY_ENV: "prod"

    project_shared_children:
      - path: "/app/sessions"
        src: "sessions"
      - path: "/app/logs"
        src: "logs"
      - path: "/web/uploads"
        src: "uploads"

    project_templates:
      - name: parameters.yml
        src: "templates/parameters.yml.j2"
        dest: "/app/config/parameters.yml"

    project_has_composer: yes

    project_post_build_commands:
      - "php vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Resources/bin/build_bootstrap.php"
      - "app/console cache:clear"
      - "app/console doctrine:migrations:migrate --no-interaction"
      - "app/console assets:install"
      - "app/console assetic:dump"

  roles:
    - f500.project_deploy

  post_tasks:
    - name: Whoohoo!
      slack: domain=future500.slack.com msg="Version {{ project_version }} of SweetlakePHP deployed on Production by {{ lookup('pipe','whoami') }}!" token={{ slack_api_token }}
