parameters:
    swp_frontend.meetupService.class: SWP\FrontendBundle\Service\MeetupService

services:
    swp_frontend.meetupService:
        class: %swp_frontend.meetupService.class%
        arguments:
            meetupClientFactory: "@dms_meetup_api.client_factory"