parameters:
    swp_frontend.meetupService.class: SWP\FrontendBundle\Service\MeetupService

services:
    swp_frontend.meetupService:
        class: %swp_frontend.meetupService.class%
        arguments:
            meetupClientFactory: "@dms_meetup_api.client_factory"
    swp_frontend.requestService:
        class: SWP\FrontendBundle\Service\RequestService
        arguments:
            container: "@service_container"
    swp_frontend.twitterService:
        class: SWP\FrontendBundle\Service\TwitterService
        arguments:
            key:         %twitter_consumer_key%
            keysecret:   %twitter_consumer_secret%
            token:       %twitter_oauth_token%
            tokenSecret: %twitter_oauth_secret%

    # Twig Extensions
    swp_frontend.menu.twig.extension:
        class: SWP\FrontendBundle\Extension\MenuExtension
        arguments:
            requestService: "@swp_frontend.requestService"
        tags:
            -  { name: twig.extension }
    swp_frontend.sidebar.twig.extension:
        class: SWP\FrontendBundle\Extension\SidebarExtension
        arguments:
            meetupService: "@swp_frontend.meetupService"
        tags:
            -  { name: twig.extension }
    swp_frontend.twitter.twig.extension:
        class: SWP\FrontendBundle\Extension\TwitterExtension
        arguments:
            twitterService: "@swp_frontend.twitterService"
        tags:
            -  { name: twig.extension }