parameters:
    swp_frontend.meetupService.class: SWP\FrontendBundle\Service\MeetupService

services:
    swp_frontend.meetupService:
        class: %swp_frontend.meetupService.class%
        arguments:
            meetupClientFactory: "@dms_meetup_api.client_factory"
            group_urlname:       "%meetup_group_urlname%"
    swp_frontend.requestService:
        class: SWP\FrontendBundle\Service\RequestService
        arguments:
            container: "@service_container"
    swp_frontend.twitterService:
        class: SWP\FrontendBundle\Service\TwitterService
        arguments:
            key:         %twitter_consumer_key%
            keysecret:   %twitter_consumer_secret%
            token:       %twitter_oauth_token%
            tokenSecret: %twitter_oauth_secret%
            rootDir:     %kernel.root_dir%
            enviorment:  %kernel.environment%
    swp_frontend.githubService:
        class: SWP\FrontendBundle\Service\GithubService
        arguments:
            username:    %github_username%
            repository:  %github_repository%
            rootDir:     %kernel.root_dir%
            enviorment:  %kernel.environment%

    # Twig Extensions
    swp_frontend.menu.twig.extension:
        class: SWP\FrontendBundle\Extension\MenuExtension
        arguments:
            requestService: "@swp_frontend.requestService"
        tags:
            -  { name: twig.extension }
    swp_frontend.sidebar.twig.extension:
        class: SWP\FrontendBundle\Extension\SidebarExtension
        arguments:
            meetupService: "@swp_frontend.meetupService"
        tags:
            -  { name: twig.extension }
    swp_frontend.contributors.twig.extension:
        class: SWP\FrontendBundle\Extension\ContributorsExtension
        arguments:
            githubService: "@swp_frontend.githubService"
        tags:
            -  { name: twig.extension }